### ISSUE TITLE
(meta) MVP: daily test rounds

### ISSUE THREAD

**Issue by autonome** [autonome/tengopreguntas#1]
Outcome: The contract, back-end and front-end are all deployed, enabling automated and on-demand running of test rounds,  and daily test rounds for ongoing interactive testing of different game types.

Contract

- [x] deploy contract to testnet

Back-end

- [x] determine where deployed
- [x] deployed to TBD

Front-end

- [x] deploy front end to IPFS

E2E testing

- [x] CI running daily

**Comment by bytesavvie** [comment]
- Verified Contracts
[[DailyPool](https://calibration.filfox.info/en/address/0x18DD5b5625C1Dff3471204e34E6BcC88F7838073?t=3)](https://calibration.filfox.info/en/address/0x18DD5b5625C1Dff3471204e34E6BcC88F7838073?t=3)
[[Test USDT](https://calibration.filfox.info/en/address/0x8cDc8c7a027f18503f4A7C24e4b7488B08A56223?t=3)](https://calibration.filfox.info/en/address/0x8cDc8c7a027f18503f4A7C24e4b7488B08A56223?t=3)

**Comment by bytesavvie** [comment]
We will use a droplet in Digitalocean to run and deploy backend

**Comment by bytesavvie** [comment]
Our domain name is [https://trivial.zone](url)
